CREATE TABLE `Benutzer` (
	`id` INT( 5 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`email` VARCHAR( 30 ) NOT NULL ,
	`password` VARCHAR( 32 ) NOT NULL ,
	`bemerkung` VARCHAR( 120 ) NOT NULL ,
	`rolle` INT( 2 ) NOT NULL
) ENGINE = MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;